### ISSUE TITLE
lock and protect does not work in one map

### ISSUE THREAD

**Issue by RocoWayne** [Muirfield/WorldProtect#3]
hi! I have been using WorldProtect some time ago without problems but now, in one map in particular in my server, it does not work at all. I lock the world and everybody is breaking and placing blocks. I have another maps with the same config and it works just fine, what can be the problem?

**Comment by Akuroma** [comment]
Try deleting the config file of the folder of your world and restart your server. Than do everything again (/wp lock ...). Do you have other protection plugins?

**Comment by RocoWayne** [comment]
Hi! The problem was that the folder was called PVP but in the level.dat the map was called PvP, so i change it and it work just fine!
